[project]
org-name = "laf"
version = "0.1.8"
authors = ["lafernando"]
repository = "https://github.com/lafernando/algorithmia"
keywords = ["algorithmia", "algorithms", "ML", "AI", "machine learning", "artificial intelligence"]
license = "Apache-2.0"
